language: java
deploy:
  provider: releases
  api_key:
    secure: Lc+GeTCIw1+Y1sA7jC7ptpwEUVLDVc8hSKzBFFjFrMbsvTzJBlTfEy4lHy9wsXBu8luE9XENG6kz+WxQU5sWfFg5SJVtGmEbixs7mw7Ek0/x7UP2+9ABnqeP9Qqd1NUWB/pHRFZjOGYzA0PSLSaRHomsxZjyGxPLw6WZvq17pjc=
  file: build/libs//xld-mustachifier-importer-plugin-1.0.0.jar
  on:
    all_branches: true
    tags: true
notifications:
  slack:
    secure: IQNhkVEVK1HSDNLRHWdP01/DMZcnk6SU5cwYFQyXaUUJo023bpyCFMdlJNpGgkf5+AINVe4jcXsXdHm3SR5rdVF2zm+/83ei2co3lAYxiGT2QcWTG+V7p4svWAqy2OyLTnXio7xXcIHmKjqxHdLNqXiuELt12a4hOgWPMkLhLXU=
