language: java
deploy:
  provider: releases
  api_key:
    secure: Lc+GeTCIw1+Y1sA7jC7ptpwEUVLDVc8hSKzBFFjFrMbsvTzJBlTfEy4lHy9wsXBu8luE9XENG6kz+WxQU5sWfFg5SJVtGmEbixs7mw7Ek0/x7UP2+9ABnqeP9Qqd1NUWB/pHRFZjOGYzA0PSLSaRHomsxZjyGxPLw6WZvq17pjc=
  file: build/libs//xld-mustachifier-importer-plugin-1.0.0.jar
  on:
    all_branches: true
    tags: true
notifications:
  hipchat:
    rooms:
      secure: T0EFV0NmJT/7Nc9PlA7zUY7ppI48wJ2M3jyTdPTfs4F0IDrfgQr6p2+iIFz+Dkyv6IXc13GN92z6xPPU6zp5yRAgNb1cP1UjfgDNP6KYMF04WLVZqvTQxBmC6QSUo4WFpN3H1Zx1oxGHEAq0V/jpMBELw+tWpAyMCfKWNJCshdQ=
